apiVersion: apps/v1
kind: Deployment
metadata:
  name: bankapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bankapp
  template:
    metadata:
      labels:
        app: bankapp
    spec:
      containers:
      - name: bankapp
        image: gowthamk3543/bankapp1:latest
        ports:
        - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: bankapp-service
spec:
  type: LoadBalancer  # This tells Kubernetes to expose the service via a load balancer
  ports:
  - port: 8088           # The port that will be exposed externally
    targetPort: 8081      # The port the container is listening on
  selector:
    app: bankapp  # This ensures the service connects to the app pods
